### ISSUE TITLE
data missing in mesh folder

### ISSUE THREAD

**Issue by erizmr** [MM-PDE/MM-PDE#1]
Hi, thanks for sharing the code!

I would like to follow the instruction in the Readme to play with the model however found that there is no 'data' in the mesh folder. Just wondering where I can get access to the these data? Thanks!

**Comment by MM-PDE** [comment]
Thanks for your interest! 

We are finalizing the cleaning of our code, and also waiting for the result of our submission. We will open-scource the final version of our code after our paper is accepted. 

We can tell you when we're done. Thank you!

**Comment by erizmr** [comment]
Thanks for the reply!

**Comment by MM-PDE** [comment]
Hi! The new code can be found at https://github.com/Peiyannn/MM-PDE.git. The datasets are also provided there. 

Thanks again for your interest!
